services:
  mongodb-container:
    image: "mongo"
    # ports:
    #   - "27017:27017"
  container-be:
    build: "./fin-ass-be"
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      MONGODB_URL: ${MONGODB_URL}
      NODE_ENV: ${NODE_ENV}
    # ports:
    #   - "4000:4000"
  container-fe:
    build: "./fin-ass-fe"
    ports:
      - "3000:3000"
    environment:
      BE_URL: ${BE_URL}